apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: angular-local

resources:
  - frontend.yaml
  - backend.yaml
  - httproute.yaml
  - backend-sealedsecret.yaml

images:
  - name: ghcr.io/0xc0dec0ffeelab/angular-frontend
    newTag: latest

  - name: ghcr.io/0xc0dec0ffeelab/angular-backend
    newTag: latest