apiVersion: argoproj.io/v1alpha1
kind: Application

metadata:
  name: prometheus
  namespace: argocd

spec:
  project: default

  source:
    repoURL: https://prometheus-community.github.io/helm-charts
    chart: prometheus
    targetRevision: 29.35.0

    helm:
      releaseName: prometheus

      valuesObject:
        alertmanager:
          enabled: false

        prometheus-pushgateway:
          enabled: false

        prometheus-node-exporter:
          enabled: false

        kube-state-metrics:
          enabled: true

        server:
          replicaCount: 1
          retention: "24h"

          persistentVolume:
            enabled: false

          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              memory: 768Mi

  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring

  syncPolicy:
    automated:
      prune: true
      selfHeal: true

    syncOptions:
      - CreateNamespace=true