# Traefik 的 Helm Chart 可建立 Gateway 與 GatewayClass，並支援其他 Namespace 的 HTTPRoute 綁定
# 這裡使用 ClusterIP，先透過 Port Forward 從 Windows 存取，不需要處理 VirtualBox 的 LoadBalancer 網路
apiVersion: argoproj.io/v1alpha1
kind: Application

metadata:
  name: traefik
  namespace: argocd

spec:
  project: default

  source:
    repoURL: https://traefik.github.io/charts
    chart: traefik
    targetRevision: 39.0.7

    helm:
      releaseName: traefik

      valuesObject:
        deployment:
          replicas: 1

        service:
          type: ClusterIP

        providers:
          kubernetesIngress:
            enabled: true

          kubernetesGateway:
            enabled: true

        gatewayClass:
          enabled: true
          name: traefik

        gateway:
          enabled: true
          name: angular-gateway

          listeners:
            web:
              port: 8000
              protocol: HTTP
              namespacePolicy:
                from: All

        resources:
          requests:
            cpu: 50m
            memory: 64Mi
          limits:
            memory: 256Mi

  destination:
    server: https://kubernetes.default.svc
    namespace: traefik

  syncPolicy:
    automated:
      prune: true
      selfHeal: true

    syncOptions:
      - CreateNamespace=true